# Generated by Django 5.0.1 on 2024-03-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='country',
        ),
    ]
