# Generated by Django 5.0.1 on 2024-03-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0002_rename_location_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='about_me',
            new_name='bio',
        ),
    ]
